name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy'     
        required: true
        default: 'dev' 
        type: choice
        options:
        - dev
        - beta
        - prod 
      version:
        description: 'Servie version'     
        required: true
        default: 1.0.0 

env:
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  PACT_SERVICE_VERSION: ${{ github.event.inputs.version }}
  PACT_SERVICE_TAG: ${{ github.event.inputs.env }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install pact
      run: make install

    - name: Run provider contract tests
      run: make provider-pact

    - name: Can I Deploy
      run: |
        pact/bin/pact-broker can-i-deploy \
          --pacticipant TestProvider \
          --broker-base-url https://hb-test.pactflow.io \
          --broker-token $PACT_BROKER_TOKEN \
          --version $PACT_SERVICE_VERSION
      