name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Servie version'     
        required: true
        default: 1.0.0 

env:
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  PACT_SERVICE_VERSION: ${{ github.event.inputs.version }}
  PACT_SERVICE_TAG: dev
  PUBLISH_VERIFICATION_RESULTS: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install pact
      run: make install

    - name: Run unit test
      run: make provider-unit

    - name: Run provider contract tests
      run: make provider-pact